### ISSUE TITLE
Add ability to bind by name

### ISSUE THREAD

**Issue by cjlucas** [oracle-dart/oracle.dart#10]
"set" methods in `Statement` should allow the user to specify the param name they specified in their query like so:

```dart

var stmt = conn.createStatement("SELECT * where foo=:bar");
stmt.setInt('bar', 1);
stmt.setInt(1, 1); // this should still also work
```

**Comment by cjlucas** [comment]
@loveridge Because dart doesnt variable parameters (or keyword arguments), the snippet you wrote would look like this:

`conn.execute("SELECT * WHERE foo=:name", {'name': variable});`

Where the 2nd parameter is a `Map`.

**Comment by loveridge** [comment]
The high level function should return a promise as well.

**Comment by loveridge** [comment]
bind by name: 6b77616a9987a5e8cea69bdeb106e56a6aa5c04b

**Comment by loveridge** [comment]
execute with map arg: cf5ece13a1e8c6dab4f8ef1cfd628478b99fe281
