### ISSUE TITLE
Add support for full NUMBER precision

### ISSUE THREAD

**Issue by cjlucas** [oracle-dart/oracle.dart#5]
Add support for 38-digit oracle NUMBERs, because we're pro.

See https://docs.oracle.com/cd/B10501_01/appdev.920/a96584/oci03typ.htm for more information.

**Comment by cjlucas** [comment]
Blocked by #15

**Comment by loveridge** [comment]
Converting to double allows 38 digit precision. See 5d64d051828dde08c6134d224b488ad16ebeed14.
